version: '3.9'
services:
  database:
    container_name: database
    image: cenoteando:database
    build:
      context: ./database
      target: database
      dockerfile: Dockerfile
    ports:
      - 8529:8529
    restart: unless-stopped
    env_file:
      - database/env/.env
    volumes:
      - /var/lib/arangodb3
      - /var/lib/arangodb3-apps

  frontend:
    container_name: frontend
    image: cenoteando:frontend
    build:
      context: ./frontend/
      target: production-stage
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - 80:80
    restart: unless-stopped
    env_file:
      - frontend/env/.env

  backend:
    container_name: backend
    image: cenoteando:backend
    build:
      context: ./backend
      target: backend
      dockerfile: Dockerfile
      args:
        PROFILE: dev
    depends_on:
      - database
    links:
      - database
    ports:
      - 8080:8080
    restart: unless-stopped
